### ISSUE TITLE
Hardware diagnostic feature

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1008]
**VVSG requirements:**
- Using the hardware Bill of Materials from Drew as a guide, set up readiness checks that can be run on-demand to determine if all the necessary hardware is correct/present and responding/not erroring? (E.g. the right model of printer, whatnot)
- Using the reporting requirements in VVSG 2 1.1.2-I/K/L to guide additional checks we should have (e.g. battery levels, toner/paper missing, etc.) Don't worry about ballot style readiness report for now - that'll be a diff ticket.
- Add the ability to run through the check/generate the report onscreen on demand (we imagine you might run this prior to L&A, to make sure you're ready, and it might be something to run right before you open polls for the same reason).

**VotingWorks requirements:**
Especially in BMD and precinct-scanner, add the ability, in poll worker screen (and possibly also on admin screen), to do a hardware diagnostic that includes:
- are all peripherals we need connected?
- are all peripherals functional? Is the card reader reading and writing correctly? Can we connect to the scanner with the driver? Is the accessible controller working appropriately?
- is the touch screen working appropriately?

Ideally, this screen can be used both for assembled production system diagnostics (after they've been stored for a while) and for individual component testing before they go into assembly line – think specifically about a diagnostic machine whose sole job is to have components plugged into it and test them.

**Tasks:**
- [ ] #1417
- [ ] Precinct Scanner: Hardware diagnostic report
- [ ] Election Manager: Hardware diagnostic report
- [ ] Central Scanner: Hardware diagnostic report

**Comment by mcchilders** [comment]
This corresponds to the VVSG 2.0 requirement 
1.1.2-A | Built-in self-test and diagnostics 
The voting system must include built-in measurement, self-testing, and diagnostic software and hardware for monitoring and reporting the system's status.

**Comment by mcchilders** [comment]
For reference, here's Drew's write-up of things he would love to have on component testing: https://docs.google.com/document/d/11q5Jci3oNSxAQjA8Wq3wYBMixah63r2uaNyaDFCluj4/edit#heading=h.te64jypn8ne5

(Ours will need to go beyond this, but helpful overlap)

**Comment by mcchilders** [comment]
Basic requirements: 
- Using the hardware Bill of Materials from Drew as a guide, set up readiness checks that can be run on-demand to determine if all the necessary hardware is present/responding/not erroring?
- Using the reporting requirements in VVSG 2 1.1.2-I/K/L to guide additional checks we should have (e.g. battery levels, toner/paper missing, etc.)

**Comment by mcchilders** [comment]
Current bills of materials are here: 
https://docs.google.com/spreadsheets/d/1YA5oasgHQeFNHSzC8nW0NWLJAPmrDBhG0QPRd7ybqAY/edit
https://docs.google.com/spreadsheets/d/1917r6rt4nLyywjzXzWZadwtuzolpilUOYePY_OgW5S8/edit
https://docs.google.com/spreadsheets/d/1VzGli5WMxl6XlZb0NLuklm-JM91cg4pyd1L7ucxrT_Q/edit
https://docs.google.com/spreadsheets/d/1THVLsf4NZiriXx32R06mUMYx-FFOb-omGNidgfbkFBU/edit

**Comment by benadida** [comment]
closing this issue out, since it's really an epic, and referring instead to the roadmap ticket:
https://github.com/votingworks/vxsuite-roadmap/issues/7
