### ISSUE TITLE
When a smart card is inserted incorrectly, tell the user

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#1349]
## Summary

When a smartcard is inserted into a card reader on any of our devices, if it's inserted in the wrong orientation, the system behaves as if no card was inserted at all, thus giving the user no visible feedback of the action or how to correct it.

As it turns out, we can tell at a low-level that a card was inserted but the chip cannot be powered up, which is almost certainly because the card was inserted in the wrong orientation. It could also happen if a non-chip card were inserted, say an old mag-stripe card, but that scenario seems unlikely and it's not the end of the world if the error message is not perfect in that case.

## Requirements

On precinct-scanner where it's most urgent, when a card is inserted and the chip cannot be powered up, display an error screen that says:

```
Card cannot be read.
Make sure the chip on the card is facing away from you.
```

On BMD, opposite message:

```
Card cannot be read.
Make sure the chip on the card is facing you.
```

## Non-Requirements

No need to present a different error message if they are using a completely incorrect card.

## Tasks

* [x] add appropriate information in the smartcard service
* [x] show the error screen in precinct-scanner
* [x] show the error screen in BMD

**Comment by beausmith** [comment]
Why not use more simple and direct language for all the screens:

> Card is Backwards
> Remove the card, rotate, and insert again.
