### ISSUE TITLE
Software Updates in the field

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1432]
## Summary
Currently the process to update software on machines is a difficult process that can only be done by Drew and/or other engineers on the team. We need something that at the very least non-engineers on the team (Charlie, Ginny, etc.) can do, and ideally customers can even do someday. 

We've got m13b equipment in the field with the ability to reboot from USB using a superadmin card. We need to complete the feature for m14 so that we can actually perform the update using "reboot from USB."

## Requirements
- We can update m13b machines in the field to m14 with minimal technical skill.

## Non-Requirements
- we don't expect customers to be able to do this yet, though one particular capable customer may be.

## Tasks
m13B 
- [x] https://github.com/votingworks/vxsuite/issues/1401 
- [x] Add "superadmin" or "vxadmin" card that shows a basic screen with a button to reboot from usb (and export logs? and unconfigure?) 

m14 
- [x] https://github.com/votingworks/vxsuite/issues/1431
- [ ] #1862
- [ ] Process for getting USBs in the field and doing the install work

**Comment by mcchilders** [comment]
@carolinemodic are the security concerns (making sure you're updating with official/unmodified Vx software, regenerating anything needed for updated system auth code, etc.) included in this card?

**Comment by mattroe** [comment]
closing in favor of the roadmap issue https://github.com/votingworks/vxsuite-roadmap/issues/9
