### ISSUE TITLE
Unified smartcard auth interface

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/vxsuite#1682]
Build a new interface to abstract all smartcard and authentication logic from the React apps.
 
**Implementation plan**
- [x] Build a prototype of this interface
- [x] Migrate bmd to the new interface
- [ ] ~~Check that we like it by implementing the card diagnostic~~ this feature was cut
- [x] Migrate the rest of the apps to the new interface

**Comment by carolinemodic** [comment]
@jonahkagan is this ready to mark as closed?

**Comment by jonahkagan** [comment]
Yes!
