### ISSUE TITLE
Make `scan` run + tests pass on Node 16

### ISSUE THREAD

**Issue by taravancil** [votingworks/vxsuite#1695]
## Summary

After upgrading to Node 16, we should be able to run `scan` and existing tests should pass.

WIP branch https://github.com/votingworks/vxsuite/tree/tara/node-16-scan

## Tasks
- [x] `pnpm build` and `pnpm start` works, and there are no obvious issues with manual QA.
- [x] `pnpm test` passes 
  - [x] #1696
- [ ] Integration tests pass in CI
