### ISSUE TITLE
VxSuite: Consistent font and emoji

### ISSUE THREAD

**Issue by beausmith** [votingworks/vxsuite#1850]
## Summary
There are discrepancies in our apps and ballots as the fonts are different in different environments. Installing a web font will ensure that the same font is always used on all of our apps and ballots.

[Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans) is the font used by VSAP and will work well for both the Vx app ui and our printed ballots.

## Requirements
- [Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans)
- [Noto Sans Emoji](https://fonts.google.com/noto/specimen/Noto+Emoji)
- Ability to have the font files in a shared lib.

## Tasks
- [x] Smoke test apps
- [x] Smoke test BMD ballot
- [x] Smoke test HMPB with variety of contests.
- [x] Check for 🕙  icon in the UI to set time.
- [x] Check for ✖️ icon in Open Polls Report.
- [ ] Confirm Debian production apps show emojis & fonts properly

**Comment by mattroe** [comment]
I didn't notice this until I locked down a machine this week. All of our fonts are annoyingly inconsistent -- agree we should definitely prioritize this.

**Comment by beausmith** [comment]
There are two ways to do this:
1. Install Noto Sans in the image
    - Available everywhere to all apps like any other font
    - Known implementation
3. Install Noto Sans as a web font
    - Implementation unknown, but probably possible.
    - Requires update to root component of each app.

**Comment by beausmith** [comment]
Resolved by https://github.com/votingworks/vxsuite/pull/2305
