### ISSUE TITLE
Sign and verify all files in and out of VotingWorks equipment

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2866]
## Summary

Every file produced by VotingWorks equipment and loaded into VotingWorks equipment should be digitally signed so they can be authenticated.

## Tasks

- [ ] design of where signature and certificate information will be stored
- [ ] design of how to check that files are properly signed at load time, e.g. CVRs
- [ ] sign CVRs files out of VxScan and VxCentralScan
- [ ] sign election definition (and ballot package?) out of VxAdmin
- [ ] verify signed CVRs when loading into VxAdmin
- [ ] verify signed election definition when loading into VxMark, VxScan, VxCentralScan
