### ISSUE TITLE
Implement challenge-based Signed Hash Validation in every component

### ISSUE THREAD

**Issue by benadida** [votingworks/vxsuite#2867]
## Summary

Every component (VxAdmin, VxMark, etc.) should provide a proof of integrity via LiveCheck, as follows:
- Prompt user to launch https://check.voting.works on their phone
- Prompt for challenge code to be entered
- Display a QR code containing a LiveCheck signature

## Tasks
- [x] core functions in library
- [x] add to VxAdmin
- [x] add to VxScan
- [x] add to VxCentralScan
- [x] add to VxMark
- [x] Incorporate system hash (computable via https://github.com/votingworks/vxsuite-complete-system/blob/main/config/admin-functions/hash-signature.sh) into signature
- [x] Add some kind of loading indicator since computing system hash can take time
- [x] Make sure we render the button for all relevant user types on all machines (https://votingworks.slack.com/archives/CJU9MSC6S/p1722349141192579)

**Comment by arsalansufi** [comment]
Using https://github.com/votingworks/vxsuite/issues/5412 to track the last change outside the certified system
