### ISSUE TITLE
Stop Using `election.json` Fixtures outside of `libs/fixtures`

### ISSUE THREAD

**Issue by adghayes** [votingworks/vxsuite#2946]
## Summary

We currently have a lot of older fixtures in places like `bmd`. The fewer fixtures we can have across the code base the better. We'd like to remove them from the following:

- [x] `apps/vx-mark/frontend`
- [ ] `libs/ballot-interpreter-vx`
- [x] `frontends/bas`
- [x] `frontends/bsd`
- [x] `frontends/election-manager`
- [ ] `integration-testing/bsd`
- [ ] `apps/vx-scan/backend`?
- [ ] `services/scan`?
- [ ] `converter-ms-sems`?

The SEMS converter may be a special case, and the scan services may be thornier and partially represented by #1524. The scan libs have the extra challenge of image fixtures, which we currently have no means to generate as needed. We can only generate ballots via a frontend, and can only generate ballots with specific features (stretched, low mark threshold) literally manually.

## Requirements

Despite the list above, I would consider this closed if we checked off all the boxes above without question marks.

## Non-Requirements

List items above with question marks.

## Tasks

See list above.

**Comment by adghayes** [comment]
Closing this due to inactivity.
