### ISSUE TITLE
Miscellaneous continuous export cleanup

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#3996]
Will open standalone issues for relevant items when I wrap up my current stretch work on continuous export.

- [ ] ~Remove [this mocking](https://github.com/votingworks/vxsuite/blob/3ba81d4d418df406aa5304fac2dbbc6e9cf159ae/libs/auth/src/artifact_authentication.test.ts#L47-L49)~ https://github.com/votingworks/vxsuite/issues/4100
- [x] Have `BallotImage` field consistently include both a front and back image, when populated
- [x] Revisit [this TODO](https://github.com/votingworks/vxsuite/blob/3ba81d4d418df406aa5304fac2dbbc6e9cf159ae/libs/backend/src/cast_vote_records/build_cast_vote_record.ts#L163-L164)
- [x] Use `*File` vs. `*FileContents` more consistently in variable names
- [x] Fix flaky tests
- [ ] ~Only flush to USB once instead of after every write when performing a full export~ https://github.com/votingworks/vxsuite/issues/4093
- [x] Remove `cvrs_backed_up_at` tracking, after verifying that it's no longer used (check both VxScan and VxCentralScan)
- [x] Make `waitForContinuousExportToUsbDrive` test helper in VxScan less arbitrary
- [x] Recovery from mid-CVR-write failures
- [x] Don't allow polls close if a mismatch is detected
- [x] Don't allow clicks outside progress modals to dismiss them
- [ ] ~Add an indication of whether CVR exports are pre- or post-polls-close~ https://github.com/votingworks/vxsuite/issues/4094
- [ ] ~Determine if `batchLabel` field is still needed and remove if possible~ https://github.com/votingworks/vxsuite/issues/4095
- [ ] ~Have recovery logic export only what needs to be exported instead of everything~ https://github.com/votingworks/vxsuite/issues/4096
- [ ] ~Update code names and variables to no longer refer to CVRs as single files~ https://github.com/votingworks/vxsuite/issues/4097
- [ ] ~Update CVR fixture generator to use actual CVR export functions~ https://github.com/votingworks/vxsuite/issues/4098
- [ ] ~Re-enable CVR auth in CVR tests~ https://github.com/votingworks/vxsuite/issues/4101
- [ ] ~Export uninterpretable rejected ballots~ https://github.com/votingworks/vxsuite/issues/4099

**Comment by arsalansufi** [comment]
Closing this issue out now that I've created standalone issues for the outstanding checklist items
